services:

  entrytracker:
    build: .
    # image: 923918898299.dkr.ecr.ap-south-1.amazonaws.com/entrytracker/entrytracker:latest
    container_name: entrytracker-app
    environment:
      DB_HOST: mysql 
      DB_USER: root   
      DB_PASSWORD: password
      DB_NAME: app_db
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
 
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on: 
          - entrytracker
          
volumes:
  db-data:
