services:

  entrytracker:
    build: .
    # image: 923918898299.dkr.ecr.ap-south-1.amazonaws.com/entrytracker/entrytracker:latest
    container_name: entrytracker-app
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}  
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition:
          service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s


  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
 
  
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - entrytracker
        
volumes:
  db-data:
